apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig
  namespace: sysdig
spec:
  chart:
    spec:
      chart: sysdig-deploy
      sourceRef:
        kind: HelmRepository
        name: sysdig
      version: 1.8.21
  interval: 1m0s